### ISSUE TITLE
Discussion: State.ts 

### ISSUE THREAD

**Issue by metaphorshear** [vend-io/vend.io#7]
What is the purpose of this class?  It doesn't seem to add anything beyond complexity.  No other files check for the current state of the machine.  Is this what you wanted the Observer pattern for?

I did notice that state.ts seems to be a controller class.  Do you think this would make more sense moved to core.ts?

**Comment by iwatakeshi** [comment]
Sorry, I don't understand by what you mean, "adding" complexity.

State class is the class that handles state.  Core should not handle the state of the machine. Core is the [context](https://dzone.com/articles/design-patterns-state). If you want to, you can rename core as "machine" if that makes it better.

**Comment by metaphorshear** [comment]
No, that's fine.  What was your plan for the Observer pattern?

**Comment by iwatakeshi** [comment]
OK. Yeah, I wanted a way to notify the UI (or front end in general) that a certain event has occurred or the state has changed. For this, I thought we could use the Observer pattern, but I couldn't think of a right way for it. So, for now, I am using an event emitter that emits on certain events such as in [payment](https://github.com/vend-io/vend.io/blob/master/src/payment.ts#L114).

**Comment by iwatakeshi** [comment]
Side note: For the State class, you can say it is a context as well but I prefer to look at it as a wrapper that decouples the Core class from the State class.
